### ISSUE TITLE
Add to the list of IPython kernels ?

### ISSUE THREAD

**Issue by Carreau** [robbielynch/ibrainfuck#1]
[in here](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages) 
and that would make this kernel the 40th of the list !

(or maybe you prefer not to). 

Thanks !

**Comment by robbielynch** [comment]
Will do.

40 kernels? Wow, that's 26 new kernels since I released IErlang one year ago!  Crazy.

Thanks!

**Comment by Carreau** [comment]
> 40 kernels? Wow, that's 26 new kernels since I released IErlang one year ago! Crazy.

Lots of them are toy example and a few "duplicates" (same language, a bit different), but yes, now 40 :-)
