### ISSUE TITLE
Demo no work is it a concern?

### ISSUE THREAD

**Issue by hcchengithub** [robbielynch/ibrainfuck#2]
Hi,
See screenshots of the problem here:
http://note.youdao.com/noteshare?id=133cf4193dc6c9f1fcb04776f1b9afed  
DEMOS's don't work! I wish they don't matter but why?

**Comment by hcchengithub** [comment]
Hi Robbie,
Your guide helped. Only the path for Windows 10 to put the kernel.json file is unclear that I have finally realized is : %USERPROFILE%\AppData\Roaming\jupyter\kernels\brainfuck\kernel.json

**Comment by robbielynch** [comment]
Hi hcchen, didn't see your request until now. Thanks for sharing the fix! :)
